sudo: required
language: python
dist: xenial

branches:
    except:
        - latest
        - stable
        - gh-pages
        - azure-pipelines

python:
    - "3.7"

cache:
    directories:
        - "slides/lecture1/tikzpics/"
        - "slides/lecture1/_minted-lecture1"
        - "slides/lecture2/tikzpics/"
        - "slides/lecture2/_minted-lecture2"
        - "slides/lecture3/tikzpics/"
        - "slides/lecture3/_minted-lecture3"
        - "slides/lecture4/tikzpics/"
        - "slides/lecture4/_minted-lecture4"
        - "slides/lecture5/tikzpics/"
        - "slides/lecture5/_minted-lecture5"
        - "slides/lecture6/tikzpics/"
        - "slides/lecture6/_minted-lecture6"
        - "slides/lecture7/tikzpics/"
        - "slides/lecture7/_minted-lecture7"
        - "slides/lecture8/tikzpics/"
        - "slides/lecture8/_minted-lecture8"
        - "slides/lecture9/tikzpics/"
        - "slides/lecture9/_minted-lecture9"
        - "/tmp/texlive"
        - "$HOME/.texlive"

before_install:
    - travis_wait 45 bash ./travis_setup.sh
    - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"

script:
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture1/lecture1.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture2/lecture2.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture3/lecture3.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture4/lecture4.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture5/lecture5.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture6/lecture6.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture7/lecture7.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture8/lecture8.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape slides/lecture9/lecture9.tex
    - latexmk -lualatex -file-line-error -cd -interaction=nonstopmode -halt-on-error -shell-escape syllabus/syllabus.tex
    - mkdir -p _build
    - tar -czf "_build/sample-data.tar.gz" data

before_deploy:
    - echo "Deploying $RELEASE_FILES to GitHub releases"
    - source travis_before_deploy.sh

deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: ghw3ui2BrizHpN9cxOuF1NumvigEeIUhY9FI4la3oAUFkt+XoCbP7swK746jBh3YU6/ILuUioorYcSktwQYqCqM15ct+Fo7xs6eFKxYEFmHRfuQBKce08piSgoGFkDZKW/oHws5lOgUkTY/sbIS+l24nu0zsicMAg2FhVU9Bq9Yjo2X5JgGQq3PbktVYibkLR9ByKYzkXCt1UsjFCZKFjoV5oBC1AGmvawcliYcjBN8UAThaiwz1rCjfn0r//3tosfMdSG0++Jbf6zEPOyv04LTcHCYo1m6nbECQI+hKR0kBTtgN18uSqKsGHQ6uJz4gPagE7nOJs0Tzwpmn3t7Ps0S3wLMjUNqmKvNYC5DaKcLZ1tzi+cZa+rznfqKnR1F7rJt+tO1J2d+VDZRooaeizS8JxCMIzhRdLIU6/7mKgPWX1fhMosIWVv0UqikrstUUKxgNWm+7WVBtnerBRc4idsk0J289LudmyMjwp0Qv94l8wqh3Pifd93bdg5+LT0NDD2f862v6UIZcbBth9QoQEtwFTzoNneHpA76MbHxhnI2OeDzkmjK/7HWxAt/fh81hJ5naLhbcM9zMM0JxeapNMhxJU0FY4+XpeCRIVOYXH7FpHtIV3QXy3z9AKMCnvGFXUN6Bqy/GRZyf9hLAfuj4yVg4DhGNbJNeK7lTXAnOo1Y=
  file_glob: true
  file:
      - slides/lecture1/lecture1.pdf
      - slides/lecture2/lecture2.pdf
      - slides/lecture3/lecture3.pdf
      - slides/lecture4/lecture4.pdf
      - slides/lecture5/lecture5.pdf
      - slides/lecture6/lecture6.pdf
      - slides/lecture7/lecture7.pdf
      - slides/lecture8/lecture8.pdf
      - slides/lecture9/lecture9.pdf
      - syllabus/syllabus.pdf
      - poly/poly.pdf
      - tools/vectorisation.py
      - _build/sample-data.tar.gz
  skip_cleanup: true
  on:
    repo: LoicGrobol/intro-fouille-textes
    branch:
        - master
        - stableb
