name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          # The root LaTeX file to be compiled
          working_directory: slides/lecture-01/
          root_file: lecture-01.tex
          args: "-lualatex -latexoption=-shell-escape -latexoption=-file-line-error -latexoption=-interaction=haltonerror"
          extra_system_packages: python3-pygments
      - name: Output all logs
        if: failure()
        run: for f in **/*.log; do cat "$f"; done;
